FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api.py .
COPY pizza_prep.json .
COPY pizza_analysis_lists.json .

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
