# ============================================================
#  מבצע מגש פיצה – OpenShift: שירותים Stateless
#  API · Kitchen Worker · Preprocessor · Enricher
# ============================================================

# ─── ConfigMap – משתני סביבה משותפים ──────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: pizza-config
data:
  MONGO_URI:        "mongodb://mongo:27017"
  REDIS_URI:        "redis://redis:6379"
  KAFKA_BOOTSTRAP:  "kafka:9092"

---
# ──────────────────────────── API ────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: pizza-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pizza-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api-route
spec:
  to:
    kind: Service
    name: api
  port:
    targetPort: 8000

---
# ──────────────────────────── Kitchen Worker ─────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen-worker
  labels:
    app: kitchen-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen-worker
  template:
    metadata:
      labels:
        app: kitchen-worker
    spec:
      containers:
        - name: kitchen-worker
          image: pizza-worker:latest
          command: ["python", "kitchen_worker.py"]
          envFrom:
            - configMapRef:
                name: pizza-config

---
# ──────────────────────────── Preprocessor ───────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessor
  labels:
    app: preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessor
  template:
    metadata:
      labels:
        app: preprocessor
    spec:
      containers:
        - name: preprocessor
          image: pizza-worker:latest
          command: ["python", "preprocessor.py"]
          envFrom:
            - configMapRef:
                name: pizza-config

---
# ──────────────────────────── Enricher ───────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enricher
  labels:
    app: enricher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enricher
  template:
    metadata:
      labels:
        app: enricher
    spec:
      containers:
        - name: enricher
          image: pizza-worker:latest
          command: ["python", "enricher.py"]
          envFrom:
            - configMapRef:
                name: pizza-config
